[package]
name = "dumb_tracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dumb_tracer_macro = { path = "./dumb_tracer_macro" }
